#!/usr/bin/python

import requests
import urllib
import os
import sys


def get_youtube(package):
    index_url = "https://www.youtube.com/results?search_query=" + package + "linux"
    response = requests.get(index_url)
    body = (response.text)

    videos = []
    lines = body.split(">")
    for line in lines:
         if "/watch?v=" in line:
             tmp = line
             tmp = tmp[:tmp.index("\" ")]
             tmp = tmp[tmp.index("=")+2:]
             if "/watch?v=" in tmp:
                 link = 'https://youtube.com' + tmp
                 videos.append(link)

    return videos
    #print(body)

if len(sys.argv) < 2:
    print('Invalid input, apt-play [package]')
    exit(0)

package = sys.argv[1]
videos = get_youtube(package)
#os.system("vlc " + videos[0])
os.system("mpv --really-quiet '" + videos[0] + "'")

