#!/usr/bin/python

import requests
import urllib
import os
import sys

def get_images(index_url):
    response = requests.get(index_url)
    body = (response.text)
    if "/screenshots/" not in body:
        return ""
        
    img = body[body.index("/screenshots/"):]
    img = img[:img.index("\"")]
    return "https://screenshots.debian.net" + img        



package = sys.argv[1]
url = get_images('https://screenshots.debian.net/package/' + package)

if len(url) > 1:
    urllib.urlretrieve(url, "tmp.jpg")
    #print(url)
    os.system("pqiv tmp.jpg")
else:
    print('No screenshot available')